'use client';

/**
 * @module useCorrelations
 *
 * React hook for fetching and filtering correlation data from the
 * correlation_cache Supabase table. Falls back to realistic mock data when
 * the table is empty or unavailable (cold-start / demo scenario).
 *
 * The hook applies client-side filtering and sorts results by a combined
 * relevance score of confidence * abs(coefficient).
 */

import { useState, useEffect, useMemo } from 'react';
import { createClient } from '@/lib/supabase/client';

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

export interface CorrelationFilters {
  /** Only include correlations involving these dimensions (empty = all). */
  dimensions?: string[];
  /** Minimum confidence score in [0, 1]. Default 0.5. */
  minConfidence?: number;
  /** Date range for the analysis window. */
  timePeriod?: '30d' | '90d' | 'all';
}

export interface CorrelationResult {
  id: string;
  feature1: string;
  feature2: string;
  dimension1: string;
  dimension2: string;
  /** Pearson / Spearman coefficient in [-1, +1]. */
  coefficient: number;
  /** Two-tailed p-value. */
  pValue: number;
  /** Composite confidence score in [0, 1]. */
  confidence: number;
  sampleSize: number;
  /** Lead time in days, null if contemporaneous. */
  lagDays: number | null;
  /** Granger causality assessment strength. */
  causalAssessment: 'suggestive' | 'moderate' | 'strong' | null;
  /** Human-readable narrative generated by the correlation engine. */
  narrative: string;
}

export interface UseCorrelationsReturn {
  correlations: CorrelationResult[];
  loading: boolean;
  error: string | null;
  /** Unique dimensions present in the result set. */
  availableDimensions: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Mock data (used when correlation_cache table is empty)
// ─────────────────────────────────────────────────────────────────────────────

const MOCK_CORRELATIONS: CorrelationResult[] = [
  {
    id: 'mock-1',
    feature1: 'sleep_hours',
    feature2: 'mood_score',
    dimension1: 'health',
    dimension2: 'health',
    coefficient: 0.72,
    pValue: 0.001,
    confidence: 0.91,
    sampleSize: 62,
    lagDays: 1,
    causalAssessment: 'moderate',
    narrative:
      'Evidence suggests that sleep duration may be associated with next-day mood. On nights where sleep exceeded 7.5 hours, mood scores were on average 1.8 points higher the following day.',
  },
  {
    id: 'mock-2',
    feature1: 'weekly_distance_km',
    feature2: 'mood_score',
    dimension1: 'fitness',
    dimension2: 'health',
    coefficient: 0.64,
    pValue: 0.003,
    confidence: 0.85,
    sampleSize: 48,
    lagDays: 2,
    causalAssessment: 'suggestive',
    narrative:
      'Higher weekly running distance appears associated with improved mood 2 days later, possibly reflecting delayed endorphin and cortisol regulation effects.',
  },
  {
    id: 'mock-3',
    feature1: 'meeting_hours',
    feature2: 'sentiment_score',
    dimension1: 'career',
    dimension2: 'health',
    coefficient: -0.58,
    pValue: 0.008,
    confidence: 0.78,
    sampleSize: 55,
    lagDays: 0,
    causalAssessment: 'suggestive',
    narrative:
      'Higher meeting load on a given day is associated with lower sentiment scores in end-of-day check-ins. Calendar fragmentation above 4 context-switches per day shows the strongest signal.',
  },
  {
    id: 'mock-4',
    feature1: 'savings_rate',
    feature2: 'mood_score',
    dimension1: 'finance',
    dimension2: 'health',
    coefficient: 0.49,
    pValue: 0.02,
    confidence: 0.72,
    sampleSize: 38,
    lagDays: 7,
    causalAssessment: 'suggestive',
    narrative:
      'Weeks with a positive savings rate are associated with higher mood scores the following week, suggesting financial security may buffer stress responses.',
  },
  {
    id: 'mock-5',
    feature1: 'social_events',
    feature2: 'mood_score',
    dimension1: 'social',
    dimension2: 'health',
    coefficient: 0.55,
    pValue: 0.01,
    confidence: 0.80,
    sampleSize: 44,
    lagDays: 1,
    causalAssessment: 'moderate',
    narrative:
      'Social calendar density shows a moderate association with next-day emotional wellbeing. The relationship is strongest for in-person events vs virtual meetings.',
  },
  {
    id: 'mock-6',
    feature1: 'focus_blocks',
    feature2: 'self_efficacy_score',
    dimension1: 'career',
    dimension2: 'growth',
    coefficient: 0.67,
    pValue: 0.002,
    confidence: 0.87,
    sampleSize: 51,
    lagDays: 0,
    causalAssessment: 'moderate',
    narrative:
      'Protected focus time in the calendar is strongly associated with higher self-efficacy scores in daily check-ins, suggesting that uninterrupted deep work reinforces a sense of personal agency.',
  },
  {
    id: 'mock-7',
    feature1: 'hrv_ms',
    feature2: 'mood_score',
    dimension1: 'health',
    dimension2: 'health',
    coefficient: 0.61,
    pValue: 0.005,
    confidence: 0.83,
    sampleSize: 46,
    lagDays: 0,
    causalAssessment: 'strong',
    narrative:
      'Heart rate variability is among the strongest physiological correlates of mood. HRV above 50ms corresponds to a mean mood lift of 1.4 points on the 10-point scale.',
  },
  {
    id: 'mock-8',
    feature1: 'financial_stress_score',
    feature2: 'sleep_hours',
    dimension1: 'finance',
    dimension2: 'health',
    coefficient: -0.53,
    pValue: 0.012,
    confidence: 0.74,
    sampleSize: 40,
    lagDays: 0,
    causalAssessment: 'suggestive',
    narrative:
      'Financial stress appears associated with shortened sleep duration. The relationship strengthens at end-of-month billing cycles and during income-uncertainty periods.',
  },
  {
    id: 'mock-9',
    feature1: 'weekly_distance_km',
    feature2: 'focus_blocks',
    dimension1: 'fitness',
    dimension2: 'career',
    coefficient: 0.45,
    pValue: 0.03,
    confidence: 0.68,
    sampleSize: 35,
    lagDays: 3,
    causalAssessment: 'suggestive',
    narrative:
      'Regular aerobic exercise may be associated with increased capacity for deep work 2-3 days later, potentially via BDNF-mediated cognitive enhancement pathways.',
  },
  {
    id: 'mock-10',
    feature1: 'meal_regularity',
    feature2: 'mood_score',
    dimension1: 'health',
    dimension2: 'health',
    coefficient: 0.42,
    pValue: 0.035,
    confidence: 0.64,
    sampleSize: 32,
    lagDays: 0,
    causalAssessment: null,
    narrative:
      'Consistent meal timing shows a weak-to-moderate association with mood stability. The signal is present but sample size is still accumulating — check back as more data is logged.',
  },
  {
    id: 'mock-11',
    feature1: 'sentiment_score',
    feature2: 'revenue_trend',
    dimension1: 'health',
    dimension2: 'finance',
    coefficient: 0.38,
    pValue: 0.04,
    confidence: 0.60,
    sampleSize: 28,
    lagDays: 14,
    causalAssessment: null,
    narrative:
      'There is a tentative association between positive sentiment in check-in text and revenue trend two weeks later. This may reflect how emotional state influences professional performance over longer timescales.',
  },
  {
    id: 'mock-12',
    feature1: 'social_events',
    feature2: 'self_efficacy_score',
    dimension1: 'social',
    dimension2: 'growth',
    coefficient: 0.51,
    pValue: 0.015,
    confidence: 0.76,
    sampleSize: 42,
    lagDays: 2,
    causalAssessment: 'suggestive',
    narrative:
      'Social engagement appears to precede increases in self-efficacy scores by approximately two days, potentially reflecting the motivational boost of social accountability and community belonging.',
  },
  {
    id: 'mock-13',
    feature1: 'steps',
    feature2: 'family',
    dimension1: 'fitness',
    dimension2: 'family',
    coefficient: 0.33,
    pValue: 0.048,
    confidence: 0.58,
    sampleSize: 30,
    lagDays: 0,
    causalAssessment: null,
    narrative:
      'Daily step count shows a weak positive association with family wellbeing scores. This may reflect shared physical activities or improved mood spillover into family interactions.',
  },
  {
    id: 'mock-14',
    feature1: 'work_hours',
    feature2: 'romance',
    dimension1: 'career',
    dimension2: 'romance',
    coefficient: -0.46,
    pValue: 0.025,
    confidence: 0.70,
    sampleSize: 36,
    lagDays: 0,
    causalAssessment: 'suggestive',
    narrative:
      'Extended work hours show a moderate negative association with romantic relationship quality scores, consistent with time-competition effects between work and partner connection.',
  },
  {
    id: 'mock-15',
    feature1: 'sleep_quality',
    feature2: 'self_efficacy_score',
    dimension1: 'health',
    dimension2: 'growth',
    coefficient: 0.59,
    pValue: 0.007,
    confidence: 0.81,
    sampleSize: 47,
    lagDays: 1,
    causalAssessment: 'moderate',
    narrative:
      'Sleep quality is one of the stronger predictors of next-day self-efficacy, suggesting that restorative sleep may be foundational to sustained personal growth behaviours.',
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Time period helpers
// ─────────────────────────────────────────────────────────────────────────────

function cutoffDate(period: '30d' | '90d' | 'all'): Date | null {
  if (period === 'all') return null;
  const d = new Date();
  d.setDate(d.getDate() - (period === '30d' ? 30 : 90));
  return d;
}

// ─────────────────────────────────────────────────────────────────────────────
// Hook implementation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetches cross-dimension correlations and provides filtered, sorted results.
 *
 * Data source priority:
 * 1. `correlation_cache` Supabase table (real data)
 * 2. Realistic mock dataset (cold-start / demo)
 *
 * @param filters - Dimension, confidence, and time-period filters
 * @returns Filtered + sorted correlations with loading/error state
 */
export function useCorrelations(filters: CorrelationFilters): UseCorrelationsReturn {
  const [rawCorrelations, setRawCorrelations] = useState<CorrelationResult[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const { dimensions = [], minConfidence = 0.5, timePeriod = '90d' } = filters;

  useEffect(() => {
    let cancelled = false;

    async function fetchCorrelations() {
      setLoading(true);
      setError(null);

      try {
        const supabase = createClient();
        const { data: { user } } = await supabase.auth.getUser();

        if (!user) {
          if (!cancelled) {
            setRawCorrelations(MOCK_CORRELATIONS);
            setLoading(false);
          }
          return;
        }

        // Build query against correlation_cache table
        let query = supabase
          .from('correlation_cache')
          .select(
            'id, feature1, feature2, dimension1, dimension2, coefficient, p_value, confidence, sample_size, lag_days, causal_assessment, narrative, computed_at',
          )
          .eq('user_id', user.id)
          .order('confidence', { ascending: false })
          .limit(200);

        // Apply server-side time filter when possible
        if (timePeriod !== 'all') {
          const cutoff = cutoffDate(timePeriod);
          if (cutoff) {
            query = query.gte('computed_at', cutoff.toISOString());
          }
        }

        const { data, error: queryError } = await query;

        if (cancelled) return;

        if (queryError) {
          // Table may not exist yet — fall back to mock data silently
          console.warn('[useCorrelations] Falling back to mock data:', queryError.message);
          setRawCorrelations(MOCK_CORRELATIONS);
        } else if (!data || data.length === 0) {
          // No real data yet — use mock data for a good cold-start experience
          setRawCorrelations(MOCK_CORRELATIONS);
        } else {
          // Map snake_case DB columns to camelCase interface
          const mapped: CorrelationResult[] = data.map((row) => ({
            id: row.id as string,
            feature1: row.feature1 as string,
            feature2: row.feature2 as string,
            dimension1: row.dimension1 as string,
            dimension2: row.dimension2 as string,
            coefficient: row.coefficient as number,
            pValue: row.p_value as number,
            confidence: row.confidence as number,
            sampleSize: row.sample_size as number,
            lagDays: row.lag_days as number | null,
            causalAssessment: row.causal_assessment as CorrelationResult['causalAssessment'],
            narrative: row.narrative as string,
          }));
          setRawCorrelations(mapped);
        }
      } catch (err) {
        if (!cancelled) {
          console.warn('[useCorrelations] Unexpected error:', err);
          setRawCorrelations(MOCK_CORRELATIONS);
          setError(null); // Don't surface errors when mock data covers it
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    fetchCorrelations();
    return () => { cancelled = true; };
  }, [timePeriod]); // Re-fetch when time period changes

  // Client-side filtering and sorting
  const correlations = useMemo(() => {
    let result = [...rawCorrelations];

    // Filter by minimum confidence
    result = result.filter((c) => c.confidence >= minConfidence);

    // Filter by selected dimensions (either dimension1 or dimension2 must match)
    if (dimensions.length > 0) {
      result = result.filter(
        (c) => dimensions.includes(c.dimension1) || dimensions.includes(c.dimension2),
      );
    }

    // Sort by composite relevance: confidence * abs(coefficient)
    result.sort((a, b) => {
      const scoreA = a.confidence * Math.abs(a.coefficient);
      const scoreB = b.confidence * Math.abs(b.coefficient);
      return scoreB - scoreA;
    });

    return result;
  }, [rawCorrelations, dimensions, minConfidence]);

  // Derive unique dimensions from unfiltered raw data
  const availableDimensions = useMemo(() => {
    const dims = new Set<string>();
    rawCorrelations.forEach((c) => {
      dims.add(c.dimension1);
      dims.add(c.dimension2);
    });
    return Array.from(dims).sort();
  }, [rawCorrelations]);

  return { correlations, loading, error, availableDimensions };
}
