/**
 * strava.ts
 *
 * Strava OAuth2 flow, activity fetching with pagination, and the full sync
 * pipeline that feeds into the feature extraction layer.
 *
 * Design notes:
 *  - Token refresh is proactive: triggered when the access token is within
 *    5 minutes of expiry.
 *  - Rate limit responses (HTTP 429) and transient server errors (5xx) are
 *    retried with truncated exponential backoff: 1s, 2s, 4s (3 attempts).
 *  - Pagination uses per_page=100 and iterates until an empty page is returned.
 *  - Raw Strava fields are mapped to the StravaActivity interface from
 *    feature-extraction.ts before extraction.
 *
 * Required environment variables:
 *   STRAVA_CLIENT_ID      — OAuth application client ID
 *   STRAVA_CLIENT_SECRET  — OAuth application client secret
 *   STRAVA_REDIRECT_URI   — Absolute callback URL
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type { StravaActivity, NormalisedFeature } from '../feature-extraction';
import { extractStravaFeatures } from '../feature-extraction';
import { storeFeatures } from './apple-health';

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

/** OAuth token bundle returned by the Strava token endpoint. */
export interface StravaTokens {
  accessToken: string;
  refreshToken: string;
  /** Unix epoch seconds at which the access token expires. */
  expiresAt: number;
  /** Strava numeric athlete identifier. */
  athleteId: number;
}

/**
 * Raw activity shape from GET /api/v3/athlete/activities.
 * Only fields we consume are listed.
 */
export interface StravaActivityRaw {
  id: number;
  name: string;
  type: string;
  start_date: string;
  elapsed_time: number;
  moving_time: number;
  distance: number;
  total_elevation_gain: number;
  average_heartrate: number | null;
  max_heartrate: number | null;
  suffer_score: number | null;
  average_speed: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────────────────────

const STRAVA_AUTH_BASE = 'https://www.strava.com/oauth/authorize';
const STRAVA_TOKEN_URL = 'https://www.strava.com/oauth/token';
const STRAVA_API_BASE = 'https://www.strava.com/api/v3';
const ACTIVITIES_PER_PAGE = 100;
const REFRESH_BUFFER_SECONDS = 300;
const MAX_RETRIES = 3;

// ─────────────────────────────────────────────────────────────────────────────
// OAuth URL construction
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Builds the Strava OAuth2 authorisation URL with activity:read_all scope.
 *
 * The state parameter should be a random CSRF token generated by the caller
 * and stored in a short-lived session cookie for validation in the callback.
 *
 * @param state - A random CSRF-protection string.
 * @returns The full Strava authorisation URL to redirect the user to.
 * @throws If STRAVA_CLIENT_ID or STRAVA_REDIRECT_URI env vars are missing.
 */
export function getStravaAuthUrl(state: string): string {
  const clientId = process.env.STRAVA_CLIENT_ID;
  const redirectUri = process.env.STRAVA_REDIRECT_URI;

  if (!clientId) {
    throw new Error('getStravaAuthUrl: STRAVA_CLIENT_ID environment variable is required.');
  }
  if (!redirectUri) {
    throw new Error('getStravaAuthUrl: STRAVA_REDIRECT_URI environment variable is required.');
  }

  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    approval_prompt: 'auto',
    scope: 'activity:read_all',
    state,
  });

  return `${STRAVA_AUTH_BASE}?${params.toString()}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Token exchange and refresh
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Exchanges a Strava authorisation code for an access + refresh token pair.
 *
 * @param code - The code query parameter from the OAuth callback.
 * @returns A StravaTokens bundle including the athlete ID.
 * @throws If the token exchange HTTP request fails.
 */
export async function exchangeStravaCode(code: string): Promise<StravaTokens> {
  const clientId = process.env.STRAVA_CLIENT_ID;
  const clientSecret = process.env.STRAVA_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error(
      'exchangeStravaCode: STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET are required.',
    );
  }

  const response = await fetch(STRAVA_TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      client_id: clientId,
      client_secret: clientSecret,
      code,
      grant_type: 'authorization_code',
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`exchangeStravaCode: token exchange failed (${response.status}): ${body}`);
  }

  return mapStravaTokenResponse(await response.json() as Record<string, unknown>);
}

/**
 * Refreshes an expired Strava access token using the stored refresh token.
 *
 * @param refreshToken - The refresh token from a previous token bundle.
 * @returns A new StravaTokens bundle with an updated access token and expiry.
 * @throws If the refresh HTTP request fails.
 */
export async function refreshStravaToken(refreshToken: string): Promise<StravaTokens> {
  const clientId = process.env.STRAVA_CLIENT_ID;
  const clientSecret = process.env.STRAVA_CLIENT_SECRET;

  if (!clientId || !clientSecret) {
    throw new Error(
      'refreshStravaToken: STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET are required.',
    );
  }

  const response = await fetch(STRAVA_TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      client_id: clientId,
      client_secret: clientSecret,
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new Error(`refreshStravaToken: token refresh failed (${response.status}): ${body}`);
  }

  return mapStravaTokenResponse(await response.json() as Record<string, unknown>);
}

// ─────────────────────────────────────────────────────────────────────────────
// Activity fetching
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetches all Strava activities within a date window, handling pagination
 * and automatic token refresh.
 *
 * Activities are fetched in batches of 100 and iteration continues until a
 * page returns fewer than 100 results. Rate limit (429) and server error (5xx)
 * responses trigger exponential backoff retries: 1s, 2s, 4s.
 *
 * @param tokens - Current Strava token bundle.
 * @param after  - Inclusive start of the date window.
 * @param before - Exclusive end of the date window.
 * @returns An array of StravaActivity objects.
 * @throws If the API returns a persistent error after all retries.
 */
export async function fetchStravaActivities(
  tokens: StravaTokens,
  after: Date,
  before: Date,
): Promise<StravaActivity[]> {
  const liveTokens = await maybeRefreshStravaTokens(tokens);

  const afterUnix = Math.floor(after.getTime() / 1000);
  const beforeUnix = Math.floor(before.getTime() / 1000);

  const allActivities: StravaActivity[] = [];
  let page = 1;

  while (true) {
    const url = new URL(`${STRAVA_API_BASE}/athlete/activities`);
    url.searchParams.set('after', String(afterUnix));
    url.searchParams.set('before', String(beforeUnix));
    url.searchParams.set('per_page', String(ACTIVITIES_PER_PAGE));
    url.searchParams.set('page', String(page));

    const rawActivities = await fetchWithRetry<StravaActivityRaw[]>(url.toString(), {
      headers: { Authorization: `Bearer ${liveTokens.accessToken}` },
    });

    allActivities.push(...rawActivities.map(mapRawActivity));

    if (rawActivities.length < ACTIVITIES_PER_PAGE) break;
    page++;
  }

  return allActivities;
}

// ─────────────────────────────────────────────────────────────────────────────
// Sync pipeline
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Full Strava sync pipeline: fetches activities since the last sync, extracts
 * normalised features, persists them, and updates the connector sync log.
 *
 * The sync window defaults to the last 8 days when no previous sync record
 * exists.
 *
 * @param userId   - UUID of the authenticated user.
 * @param supabase - Supabase client with appropriate permissions.
 * @param tokens   - Current Strava token bundle.
 * @returns Object with recordsProcessed count and extracted features array.
 * @throws If the Strava API or Supabase calls fail irrecoverably.
 */
export async function syncStrava(
  userId: string,
  supabase: SupabaseClient,
  tokens: StravaTokens,
): Promise<{ recordsProcessed: number; features: NormalisedFeature[] }> {
  const now = new Date();
  const lastSync = await getLastSyncDate(supabase, userId, 'strava');
  const syncFrom = lastSync ?? new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000);

  const activities = await fetchStravaActivities(tokens, syncFrom, now);

  let features: NormalisedFeature[] = [];
  if (activities.length > 0) {
    features = extractStravaFeatures(activities);
    await storeFeatures(supabase, userId, features);
  }

  await upsertSyncLog(supabase, userId, 'strava', {
    recordsProcessed: activities.length,
    syncedAt: now,
    status: 'success',
  });

  return { recordsProcessed: activities.length, features };
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns refreshed tokens if the current access token is within
 * REFRESH_BUFFER_SECONDS of expiry; otherwise returns the original tokens.
 */
async function maybeRefreshStravaTokens(tokens: StravaTokens): Promise<StravaTokens> {
  const nowSeconds = Math.floor(Date.now() / 1000);
  if (tokens.expiresAt - nowSeconds <= REFRESH_BUFFER_SECONDS) {
    return refreshStravaToken(tokens.refreshToken);
  }
  return tokens;
}

/**
 * Executes a fetch with exponential backoff retry for 429 and 5xx responses.
 *
 * @param url     - The request URL.
 * @param options - Standard RequestInit options.
 * @returns Parsed JSON body as type T.
 * @throws After MAX_RETRIES exhausted or a non-retryable error.
 */
async function fetchWithRetry<T>(url: string, options: RequestInit): Promise<T> {
  let lastError: Error = new Error('fetchWithRetry: no attempts made');

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const response = await fetch(url, options);

    if (response.ok) {
      return response.json() as Promise<T>;
    }

    if (response.status === 429 || response.status >= 500) {
      lastError = new Error(
        `fetchWithRetry: HTTP ${response.status} on attempt ${attempt + 1}`,
      );
      if (attempt < MAX_RETRIES - 1) {
        const delayMs = 1000 * Math.pow(2, attempt);
        await sleep(delayMs);
      }
      continue;
    }

    const body = await response.text();
    throw new Error(`fetchWithRetry: HTTP ${response.status}: ${body}`);
  }

  throw lastError;
}

/**
 * Maps a raw Strava API activity to the StravaActivity interface.
 *
 * @param raw - Raw activity object from the API.
 * @returns A StravaActivity compatible with extractStravaFeatures.
 */
function mapRawActivity(raw: StravaActivityRaw): StravaActivity {
  return {
    type: raw.type,
    distanceMeters: raw.distance,
    movingTimeSeconds: raw.moving_time,
    startDate: new Date(raw.start_date),
    averageHeartRate: raw.average_heartrate ?? undefined,
    maxHeartRate: raw.max_heartrate ?? undefined,
    sufferedScore: raw.suffer_score ?? undefined,
  };
}

/**
 * Maps a Strava token endpoint response to a typed StravaTokens bundle.
 *
 * @param data - Raw JSON from the Strava token endpoint.
 * @returns A StravaTokens object.
 */
function mapStravaTokenResponse(data: Record<string, unknown>): StravaTokens {
  return {
    accessToken: data.access_token as string,
    refreshToken: data.refresh_token as string,
    expiresAt: data.expires_at as number,
    athleteId:
      ((data.athlete as Record<string, unknown> | undefined)?.id as number | undefined) ?? 0,
  };
}

/**
 * Queries connector_sync_log for the most recent successful sync timestamp.
 *
 * @param supabase - Supabase client.
 * @param userId   - User UUID.
 * @param provider - Provider key.
 * @returns Date of the last successful sync, or null if no record exists.
 */
async function getLastSyncDate(
  supabase: SupabaseClient,
  userId: string,
  provider: string,
): Promise<Date | null> {
  const { data } = await supabase
    .from('connector_sync_log')
    .select('synced_at')
    .eq('user_id', userId)
    .eq('provider', provider)
    .eq('status', 'success')
    .order('synced_at', { ascending: false })
    .limit(1)
    .single();

  if (!data?.synced_at) return null;
  return new Date(data.synced_at as string);
}

/**
 * Inserts a sync run record into the connector_sync_log table.
 *
 * Failures are non-fatal — logged but not re-thrown.
 */
async function upsertSyncLog(
  supabase: SupabaseClient,
  userId: string,
  provider: string,
  payload: { recordsProcessed: number; syncedAt: Date; status: string },
): Promise<void> {
  const { error } = await supabase.from('connector_sync_log').insert({
    user_id: userId,
    provider,
    records_processed: payload.recordsProcessed,
    synced_at: payload.syncedAt.toISOString(),
    status: payload.status,
    event: 'sync',
  });

  if (error) {
    console.warn(`upsertSyncLog: failed to write sync log for ${provider} — ${error.message}`);
  }
}

/** Resolves after ms milliseconds. */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
